### ISSUE TITLE
No custom theme throws error

### ISSUE THREAD

**Issue by peterjaap** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#40]
I am upgrading a shop that does not have a custom theme (because it's a PWA store). But the patch helper not only checks themes, but also preferences and plugins, which I want to check.

It now gives;

```

In Magento2Instance.php line 100:
                                  
  Unable to find custom theme(s)  
                                  

analyse [-a|--auto-theme-update [AUTO-THEME-UPDATE]] [--sort-by-type] [--vendor-namespaces [VENDOR-NAMESPACES]] [--php-strict-errors] [--] <project>

```

When I comment out the exception throwing in https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/master/src/Ampersand/PatchHelper/Helper/Magento2Instance.php#L100, it does work;

```
+------+------+----------+
| Type | Core | To Check |
+------+------+----------+
You should review the above 0 items alongside ../client/magento2/vendor_files_to_check.patch

```

So in my opinion this shouldn't be an exception, but maybe a warning notice?

**Comment by convenient** [comment]
@peterjaap I agree
 
I think we can remove this section entirely

https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/980e800f908a2ce937298ebda579d0c126aeaa1e/src/Ampersand/PatchHelper/Helper/Magento2Instance.php#L99-L101

Because the themes data stores are initialised as empty arrays here
https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/980e800f908a2ce937298ebda579d0c126aeaa1e/src/Ampersand/PatchHelper/Helper/Magento2Instance.php#L20-L24

When we have no themes we iterate over in this section 
https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/980e800f908a2ce937298ebda579d0c126aeaa1e/src/Ampersand/PatchHelper/Helper/PatchOverrideValidator.php#L378-L393

To me this seems safe, I have raised #41. Do you agree the changes in #41 will fix your issue?

**Comment by peterjaap** [comment]
@convenient agreed, that's what I did locally too :)

**Comment by convenient** [comment]
Thanks for the issue @peterjaap
