### ISSUE TITLE
Email template support

### ISSUE THREAD

**Issue by BorisovskiP** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#62]
When updating to 2.4.3p-2 and above, we noticed that the the tool did not show email template changes. 

For example, a change in `vendor/magento/module-customer/view/frontend/email/password_reset_confirmation.html` did not come up when using the tool. We have an overwrite on this template file and noticed we were missing a parameter only after we got an issue with the emails.

Does this tool support email templates? If not, is the a plan to add it in the near future?

**Comment by convenient** [comment]
Can you provide an example override path ? Would make it a bit quicker to whip up a test case

**Comment by BorisovskiP** [comment]
We have our custom code under `src/TestProject/Theme/Magento_Customer/email/password_reset_confirmation.html`.

**Comment by BorisovskiP** [comment]
Hey @convenient did you manage to reproduce the issue ?

**Comment by convenient** [comment]
Hey @BorisovskiP 

I tried but needed to revamp how the automated test suites work to support php 8.1 😅  as you can see they've started failing in the main branch probably because of some untightly bound composer dependency and the fact that the tests ran with `--ignore-platform-reqs` 

Feeling very much like this GIF atm https://c.tenor.com/ENgHABC0E60AAAAC/bryan-cranston-replace-the-bulb.gif
![hal fixing a lightbulb](https://c.tenor.com/ENgHABC0E60AAAAC/bryan-cranston-replace-the-bulb.gif)

Once i get the suite going green again I should be more readily able to repro this issue thanks for your patience

**Comment by BorisovskiP** [comment]
The GIF gave me a good laugh :smile: . Sure, keep me posted.

**Comment by BorisovskiP** [comment]
@convenient Thanks, we will test it and come back to you if we find some issues.

**Comment by convenient** [comment]
Thanks @BorisovskiP 

I got it captured in a test case okay, so hopefully no issues :) (Provided magento doesnt vary the path and always stores in `Theme/Magento_Module/email/foobar.html` 🤞 )

**Comment by convenient** [comment]
@BorisovskiP just checking if you reviewed? np if not as i think the tests cover it
